global:
  env: test
  domain: getspeakhub.com
  envPrefix: staging-gsh
  clusterDomain: svc.cluster.local

core:
  mountedDirectory: ""

databases:
  mongoServiceName: mongo
  postgresServiceName: postgres
  postgresPort: 5432
  redisServiceName: redis
  redisPort: 6379

services:
  notificationName: notification-service
  getSpeakHubName: getspeakhub-service
  oauthResourceName: user-resource-service
  logstashName: logstash

auth:
  facebookEnabled: "false"
  googleEnabled: "false"
  googleAdminClientId: ""

notification:
  emailDirectory: templates/email/getspeakhub/
  emailSender: NoReply <noreply@getspeakhub.com>
  smtp:
    url: smtp.resend.com
    port: 587
    username: resend

gateway:
  mountedDirectory: ""
