serviceType: portal

replicaCount: 1

image:
  repository: ghcr.io/burakbalim/get-speakhub-portal
  pullPolicy: Always
  tag: latest
  pullSecret: ghcr-secret

ingress:
  enabled: true
  items:
    - internal-ingress

ingress_path: "/"

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: "getspeakhub-portal"

service:
  fullname: "getspeakhub-portal"
  type: ClusterIP
  port: 80
  serviceAccountName: "getspeakhub-portal"

nameOverride: "getspeakhub-portal"
fullnameOverride: "getspeakhub-portal"

podAnnotations: {}
podLabels:
  app.type: frontend
podSecurityContext: {}
securityContext: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

resources: {}
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
