apiVersion: v1
kind: ConfigMap
metadata:
  name: smtp-config
  labels:
    app.kubernetes.io/component: smtp
data:
  SMTP_MAIL_URL: "{{ .Values.notification.smtp.url }}"
  SMTP_MAIL_PORT: {{ .Values.notification.smtp.port | quote }}
  SMTP_USERNAME: "{{ .Values.notification.smtp.username }}"
  EMAIL_TEMPLATE_DIRECTORY: "{{ .Values.notification.emailDirectory }}"
