apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
  labels:
    app.kubernetes.io/component: core
data:
  PROXY_TARGET: "apigw.{{ .Values.global.envPrefix }}.{{ .Values.global.domain }}"
  APP_ENV: "{{ .Values.global.env }}"
