replicaCount: 1

image:
  repository: ghcr.io/burakbalim/messaging-service
  pullPolicy: Always
  tag: latest
  pullSecret: ghcr-secret

env:
  - name: "JAVA_OPTS"
    value: "-Dspring.profiles.active=test"

configs:
  - service-test-config

secrets:
  - service-test-secret

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: "messaging-service"

service:
  fullname: "messaging-service"
  type: ClusterIP
  port: 80
  serviceAccountName: "messaging-service"

ingress:
  enabled: true
  customNamespace:
    enabled: false
  className: "nginx"
  defaultPath: "/"
  defaultPathType: "Prefix"
  annotations: {}
  hosts:
    - host: "api.staging.int.getspeakhub.com"
      paths:
        - path: /messaging-service
          pathType: Prefix
  tls: []


nameOverride: "messaging-service"
fullnameOverride: "messaging-service"

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

resources: {}
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
