serviceType: apigw

replicaCount: 1

image:
  repository: ghcr.io/burakbalim/api-gw
  pullPolicy: Always
  tag: latest
  pullSecret: ghcr-secret

env:
  - name: "JAVA_OPTS"
    value: "-Dspring.profiles.active=test --enable-preview"

configs:
  - auth-config
  - core-config
  - db-config
  - service-config
  - gateway-config


secrets:
  - db-secret


volumes:
  - name: gateway-config-volume
    projected:
      sources:
        - configMap:
            name: gateway-internal-config
        - secret:
            name: oauth2-secret-config

volumeMounts:
  - name: gateway-config-volume
    mountPath: /configuration


ingress:
  enabled: true
  items:
    - external-ingress

ingress_path: "/"

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: "helm-deployer"

service:
  fullname: "api-gw"
  type: ClusterIP
  port: 80
  serviceAccountName: "helm-deployer"

nameOverride: "api-gw"
fullnameOverride: "api-gw"

podAnnotations: {}
podLabels:
  app.type: api
podSecurityContext: {}
securityContext: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
