serviceType: apigw

replicaCount: 1

image:
  repository: ghcr.io/burakbalim/api-gw
  pullPolicy: Always
  tag: latest
  pullSecret: ghcr-secret

env:
  - name: "JAVA_OPTS"
    value: "-Dspring.profiles.active=test --enable-preview"

configs:
  - cm-auth
  - cm-core
  - cm-database
  - cm-service

secrets:
  - service-test-secret

ingress:
  enabled: true
  items:
    - external-ingress

ingress_path: "/gw"

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: "helm-deployer"

service:
  fullname: "api-gw"
  type: ClusterIP
  port: 80
  serviceAccountName: "helm-deployer"

nameOverride: "api-gw"
fullnameOverride: "api-gw"

podAnnotations: {}
podLabels:
  app.type: api
podSecurityContext: {}
securityContext: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

resources: {}
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
