{{- $namespace := .Release.Namespace }}
  {{- $modeNamespace := .Values.global.mode_namespace | default false }}

  {{- range $ingressName, $ingressData := .Values.global.ingressCatalog }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingressName }}
  namespace: {{ $namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ $ingressData.ingressClass }}
    # Eğer TLS için cert-manager kullanıyorsanız:
    {{- if $ingressData.tlsEnabled }}
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    {{- end }}
spec:
  {{- if $ingressData.tlsEnabled }}
  tls:
    - hosts:
      # --- DOMAIN HESAPLAMA (TLS) ---
      {{- if $modeNamespace }}
      - {{ $namespace }}.{{ $ingressData.baseDomain }}
      {{- else }}
      - {{ $ingressData.domain }}
      {{- end }}
      secretName: {{ $ingressName }}-tls
  {{- end }}
  rules:
  # --- DOMAIN HESAPLAMA (RULES) ---
  {{- if $modeNamespace }}
  - host: {{ $namespace }}.{{ $ingressData.baseDomain }}
  {{- else }}
  - host: {{ $ingressData.domain }}
  {{- end }}
  http:
    paths:
      - path: {{ $ingressData.path }}
        pathType: Prefix
        backend:
          service:
            # Not: Servis ismini ingress adından veya values'dan türetebilirsiniz.
            name: {{ $ingressName }}-svc
            port:
              number: 80
  {{- end }}
