serviceType: api

replicaCount: 1

image:
  repository: ghcr.io/burakbalim/user-resource-service
  pullPolicy: Always
  tag: latest
  pullSecret: ghcr-secret

env:
  - name: "JAVA_OPTS"
    value: "-Dspring.profiles.active=test"

configs:
  - auth-config
  - core-config
  - db-config
  - service-config

secrets:
  - db-secret

ingress:
  enabled: true
  items:
    - internal-ingress

ingress_path: "/user-resource-service"

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: "user-resource-service"

service:
  fullname: "user-resource-service"
  type: ClusterIP
  port: 80
  serviceAccountName: "user-resource-service"


nameOverride: "user-resource-service"
fullnameOverride: "user-resource-service"

podAnnotations: {}
podLabels:
  app.type: api
podSecurityContext: {}
securityContext: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

resources: {}
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
