apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    app.kubernetes.io/component: database
data:
  MONGO_HOST: "{{ .Values.databases.mongoServiceName }}.{{ .Release.Namespace }}.{{ .Values.global.clusterDomain }}"
  POSTGRES_HOST: "{{ .Values.databases.postgresServiceName }}.{{ .Release.Namespace }}.{{ .Values.global.clusterDomain }}:{{ .Values.databases.postgresPort }}"
  REDIS_HOST: "{{ .Values.databases.redisServiceName }}.{{ .Release.Namespace }}.{{ .Values.global.clusterDomain }}"
  REDIS_PORT: {{ .Values.databases.redisPort | quote }}
