apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mychart.fullname" . }}-smtp-config
  labels:
    app.kubernetes.io/component: smtp
data:
  SMTP_MAIL_URL: "{{ .Values.smtp.url }}"
  SMTP_MAIL_PORT: "{{ .Values.smtp.port | quote }}"
  SMTP_USERNAME: "{{ .Values.smtp.username }}"
