serviceType: app

replicaCount: 1

image:
  repository: ghcr.io/burakbalim/getspeakhub-ui
  pullPolicy: Always
  tag: latest
  pullSecret: ghcr-secret

env:
  - name: "API_GATEWAY_URL"
    value: "/api"
  - name: "APP_ENV"
    value: "test"
  - name: "APP_VERSION"
    value: "1.0.0"


ingress:
  enabled: true
  items:
    - internal-ingress

ingress_path: "/"

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: "getspeakhub-ui"

service:
  fullname: "getspeakhub-ui"
  type: ClusterIP
  port: 80
  serviceAccountName: "getspeakhub-ui"

nameOverride: "getspeakhub-ui"
fullnameOverride: "getspeakhub-ui"

podAnnotations: {}
podLabels:
  app.type: frontend
podSecurityContext: {}
securityContext: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

resources: {}
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
