{{- $namespace := .Release.Namespace }}
{{- $catalog := .Values.global.ingressCatalog }}
{{- $serviceType := .Values.serviceType | default "" }}
{{- $ingressList := .Values.ingress }}
{{- if kindIs "map" .Values.ingress }}
  {{- $ingressList = .Values.ingress.items }}
{{- end }}

{{- range $ingressName := $ingressList }}
{{- $ingressData := index $catalog $ingressName }}
{{- if $ingressData }}

  {{- $finalPath := $.Values.ingress_path | default "/" }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-{{ $ingressName }}
  namespace: {{ $namespace }}
  annotations:
    {{- if $ingressData.tlsEnabled }}
    cert-manager.io/cluster-issuer: {{ $.Values.global.clusterIssuer | default "letsencrypt-prod" | quote }}
    {{- end }}
spec:
  ingressClassName: {{ $ingressData.ingressClass }}
  {{- if $ingressData.tlsEnabled }}
  tls:
    - hosts:
      {{- if $serviceType }}
      - {{ $serviceType }}.{{ $namespace }}.{{ $ingressData.baseDomain }}
      {{- else }}
      - {{ $namespace }}.{{ $ingressData.baseDomain }}
      {{- end }}
      secretName: {{ $.Release.Name }}-{{ if $serviceType }}{{ $serviceType }}-{{ end }}{{ $ingressName }}-tls
  {{- end }}
  rules:
  {{- if $serviceType }}
  - host: {{ $serviceType }}.{{ $namespace }}.{{ $ingressData.baseDomain }}
    http:
      paths:
        - path: {{ $finalPath }}
          pathType: Prefix
          backend:
            service:
              name: {{ include "service.fullname" $ }}
              port:
                number: {{ $.Values.service.port }}
  {{- else }}
  - host: {{ $namespace }}.{{ $ingressData.baseDomain }}
    http:
      paths:
        - path: {{ $finalPath }}
          pathType: Prefix
          backend:
            service:
              name: {{ include "service.fullname" $ }}
              port:
                number: {{ $.Values.service.port }}
  {{- end }}
  {{- end }}
  {{- end }}
