replicaCount: 1

image:
  repository: ghcr.io/burakbalim/notification-service
  pullPolicy: Always
  tag: latest
  pullSecret: ghcr-secret

env:
  - name: "JAVA_OPTS"
    value: "-Dspring.profiles.active=test"

configs:
  - auth-config
  - core-config
  - db-config
  - service-config
  - smtp-config

secrets:
  - db-secret

ingress:
  enabled: true
  items:
    - internal-ingress

ingress_path: "/notification-service"

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: "notification-service"

service:
  fullname: "notification-service"
  type: ClusterIP
  port: 80
  serviceAccountName: "notification-service"

nameOverride: "notification-service"
fullnameOverride: "notification-service"

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

resources: {}
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
