serviceType: api

replicaCount: 1

image:
  repository: ghcr.io/burakbalim/messaging-history-service
  pullPolicy: Always
  tag: latest
  pullSecret: ghcr-secret

env:
  - name: "JAVA_OPTS"
    value: "-Dspring.profiles.active=test"

configs:
  - service-test-config

secrets:
  - service-test-secret

ingress:
  enabled: true
  items:
    - internal-ingress

ingress_path: "/messaging-history-service"

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: "messaging-history-service"

service:
  fullname: "messaging-history-service"
  type: ClusterIP
  port: 80
  serviceAccountName: "messaging-history-service"

nameOverride: "messaging-history-service"
fullnameOverride: "messaging-history-service"

podAnnotations: {}
podLabels:
  app.type: api
podSecurityContext: {}
securityContext: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80

resources: {}
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
