replicas: 1

fullnameOverride: "postgres"

image:
  repository: postgres
  tag: "15"

service:
  type: ClusterIP

storage:
  storageClass: local-storage-delete
  size: "20Gi"

postgresqlConfig:
  listen_addresses = '*'
  max_connections = 200
  shared_buffers = 256MB
  wal_level = replica
  max_wal_senders = 3
  max_replication_slots = 10
  wal_keep_size = 64MB
  hot_standby = on
  max_idle_in_transaction_session_timeout = 300000
  idle_in_transaction_session_timeout = 300000
  tcp_keepalives_idle = 900
  tcp_keepalives_interval = 30
  tcp_keepalives_count = 5


pgHbaConfig:
  local   all             all                                    trust
  host    all             all             0.0.0.0/0              trust
  host    replication     postgres        0.0.0.0/0              trust


